//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

// File generated on 21.09.2016 20:04:38
namespace DirOnline
{
    using System;
    
    
    public sealed class WaveContent
    {
        
        public sealed class Assets
        {
            
            public sealed class Fonts
            {
                
                /// <summary> Path to Content/Assets/Fonts/Title_16.ttf </summary>
                public const string Title_16_ttf = "Content/Assets/Fonts/Title_16.ttf";
            }
            
            public sealed class UI
            {
                
                /// <summary> Path to Content/Assets/UI/6-01-200x200.png </summary>
                public const string _6_01_200x200_png = "Content/Assets/UI/6-01-200x200.png";
            }
        }
        
        public sealed class Scenes
        {
            
            /// <summary> Path to Content/Scenes/MyScene.wscene </summary>
            public const string MyScene = "Content/Scenes/MyScene.wscene";
        }
    }
}
